### PR TITLE
Allow temp dir name override

### PR DESCRIPTION
**Pull request by Omar007**
Allow for the temp directory the Image Tool uses to be overridden and specified by the user using an environment variable. This makes it possible to pin the directory used, making it now possible to pin all the directories the Image Tool uses to specific paths.

As this directory is also used as the Docker build context, this also allows for preparing additional files in advance to be included and thus be available during the different additionalBuildCommands stages. This would be a solution for #106 .

### CODE REVIEW

**Comment by ddsharpe** [comment]
This change is overriding the WLSIMG_BLDDIR environment variable which would make it a little confusing to some users.  I was going to add an option --additionalBuildFiles to fix #106 with the next enhancement release.  Is #106 the only reason for this change?  Would the addition of --additionalBuildFiles suffice?

**Comment by Omar007** [comment]
The --additionalBuildFiles flag sounds like it should be enough to cover #106 .
This change is not (just) about that though. This change would allow for specific folders within the whole build process. It is not overriding WLSIMG_BLDDIR but the directory being used/created inside the path defined with WLSIMG_BLDDIR (by default a temp dir with the 'wlsimgbuilder_temp' prefix).
The full predictable path when setting the new variable would be $WLSIMG_BLDDIR/$WLSIMG_BLDTMPDIRNAME.

**Comment by Omar007** [comment]
The idea was to allow for more caching in automated build pipelines by combining this with `--skipcleanup` but checking more, it seems it is still copying over the files regardless of whether or not the file already exists. To complete that change it looks like I'd still need to make a change in 'handleInstallerFiles' as well.

**Comment by ddsharpe** [comment]
@Omar007 I cannot find your name on the approved list of contributors, https://www.oracle.com/technetwork/community/oca-486395.html

Please read the Contributing doc provided in the project.  https://github.com/oracle/weblogic-image-tool/blob/master/CONTRIBUTING.md.  We need this form submitted, and the commit signed by any contributors.

**Comment by Omar007** [comment]
I can't exactly sign that as an Oracle employee..

> I am signing on behalf of myself as an individual and no other person or entity, including my employer, has or will have rights with respect my contributions.  
With my employer being Oracle, they will have the rights to my contributions.

And:
> I am signing on behalf of my employer or a legal entity and I have the actual authority to contractually bind that entity.  
I do not in any way have authority to do so.

So I guess I'll just have to drop this then :confused:

**Comment by markxnelson** [comment]
Oracle employees do not have to sign the OCA.  There are a different set of requirements for Oracle employees.

**Comment by markxnelson** [comment]
@Omar007 please send me an email and I will point you to the right info. mark.x.nelson at oracle.com

**Comment by ddsharpe** [comment]
@Omar007 were you able to connect with @markxnelson to get the information that you need?

**Comment by ddsharpe** [comment]
Closing, enhancement rejected.

**Pull request closed without merging**
